In [25]:
import numpy as np

In [2]:
arr=np.array([1,2,3])

In [3]:
arr

array([1, 2, 3])

In [4]:
arr1=np.array([[1,2,3],[5,6,7]])

In [5]:
arr1

array([[1, 2, 3],
       [5, 6, 7]])

In [8]:
arr2=np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [9]:
arr2

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [11]:
arr.ndim

1

In [12]:
arr2.ndim

3

In [13]:
arr1.ndim

2

In [14]:
arr[2]

3

In [15]:
arr2[0][2]

array([7, 8, 9])

In [16]:
arr.shape

(3,)

In [17]:
arr4=np.arange(1,11)

In [18]:
arr4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
arr5=np.arange(10,21)

In [20]:
arr5

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [24]:
zero_matrix=np.zeros((3,3))

In [1]:
import numpy as np

In [2]:
a=np.arange(4)

In [3]:
a

array([0, 1, 2, 3])

In [4]:
b=np.arange(4,8)

In [5]:
b

array([4, 5, 6, 7])

In [6]:
c=a+b

In [7]:
c

array([ 4,  6,  8, 10])

In [8]:
a*b

array([ 0,  5, 12, 21])

In [9]:
a-b

array([-4, -4, -4, -4])

In [10]:
a>3

array([False, False, False, False])

In [11]:
a>2

array([False, False, False,  True])

In [12]:
e=np.arange(12)

In [13]:
e

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [15]:
f=e.reshape(3,4)

In [16]:
f

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [17]:
f.min()

0

In [18]:
f.max()

11

In [19]:
f.mean()

5.5

In [20]:
f.sum(axis=0)

array([12, 15, 18, 21])

In [21]:
f.sum(axis=(1))

array([ 6, 22, 38])

In [24]:
n=np.random.rand(3,4)

In [25]:
n

array([[0.54838841, 0.97039401, 0.05394486, 0.2534983 ],
       [0.11487497, 0.73932059, 0.8556706 , 0.84244098],
       [0.29634737, 0.65280926, 0.63418514, 0.88214987]])

In [26]:
m=n.reshape(4,3)

In [27]:
m

array([[0.54838841, 0.97039401, 0.05394486],
       [0.2534983 , 0.11487497, 0.73932059],
       [0.8556706 , 0.84244098, 0.29634737],
       [0.65280926, 0.63418514, 0.88214987]])

In [28]:
m=n.reshape(6,2)

In [29]:
m

array([[0.54838841, 0.97039401],
       [0.05394486, 0.2534983 ],
       [0.11487497, 0.73932059],
       [0.8556706 , 0.84244098],
       [0.29634737, 0.65280926],
       [0.63418514, 0.88214987]])

In [30]:
l=n.ravel()

In [31]:
l

array([0.54838841, 0.97039401, 0.05394486, 0.2534983 , 0.11487497,
       0.73932059, 0.8556706 , 0.84244098, 0.29634737, 0.65280926,
       0.63418514, 0.88214987])

In [33]:
a=np.arange(4).reshape(2,2)

In [34]:
a

array([[0, 1],
       [2, 3]])

In [36]:
b=np.arange(4,8).reshape(2,2)

In [37]:
b

array([[4, 5],
       [6, 7]])

In [38]:
v=np.vstack((a,b))

In [39]:
v

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [40]:
x=np.hstack((a,b))

In [41]:
x

array([[0, 1, 4, 5],
       [2, 3, 6, 7]])

In [42]:
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [64]:
e=np.array(['apple','orange','grape'])

In [65]:
e

array(['apple', 'orange', 'grape'], dtype='<U6')

In [66]:
d=np.array(['apple','orange','grape'],dtype='S')

In [67]:
d

array([b'apple', b'orange', b'grape'], dtype='|S6')

In [68]:
y=e.astype('S')

In [69]:
y

array([b'apple', b'orange', b'grape'], dtype='|S6')

In [70]:
q=e.copy()

In [72]:
q

array(['apple', 'orange', 'grape'], dtype='<U6')

In [73]:
q[0]='banana'

In [74]:
q

array(['banana', 'orange', 'grape'], dtype='<U6')

In [75]:
e

array(['apple', 'orange', 'grape'], dtype='<U6')

In [76]:
m=e.view()

In [77]:
m[0]='jack'

In [78]:
m

array(['jack', 'orange', 'grape'], dtype='<U6')

In [79]:
e

array(['jack', 'orange', 'grape'], dtype='<U6')

In [80]:
arr1=np.array([1,2,3])

In [81]:
arr2=np.array([4,5,6])

In [82]:
arr=np.concatenate((arr1,arr2))

In [83]:
arr

array([1, 2, 3, 4, 5, 6])