In [1]:
import numpy as np

In [4]:
arr=np.array([1,2,3])

In [5]:
arr

array([1, 2, 3])

In [6]:
arr2=np.array([[1,2,3],[4,5,6]])

In [7]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
arr3=np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [15]:
arr3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [10]:
arr.ndim      #dim denotes dimentions

1

In [11]:
arr2.ndim     #denotes raws ne parayan patulla bracket nokkiyal manasilavum 

2

In [8]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
arr[2]

3

In [10]:
arr

array([1, 2, 3])

In [11]:
arr[0]

1

In [16]:
arr3[0][0]

array([1, 2, 3])

In [17]:
arr.shape

(3,)

In [20]:
arr5=np.arange(1,11)

In [21]:
arr5

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
arr6=np.arange(10,21)

In [25]:
arr6

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [26]:
arr7=np.arange(10,21,2)

In [27]:
arr7

array([10, 12, 14, 16, 18, 20])

In [28]:
zero_matri=np.zeros((3,3))
zero_matri

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [29]:
one_matri=np.ones((4,4))

In [30]:
one_matri

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [31]:
random_matrix=np.random.rand(4,4)    #b/w 0 and 1

In [32]:
random_matrix

array([[0.71328983, 0.02871615, 0.19330383, 0.66335333],
       [0.5493189 , 0.50486955, 0.38919812, 0.86273412],
       [0.84202757, 0.42067695, 0.43763934, 0.32759153],
       [0.57625088, 0.77939499, 0.88638024, 0.1187033 ]])

In [33]:
random_matrix2=np.random.randint(1,11,size=(3,3))  #random ayyit 1 to 11

In [34]:
random_matrix2

array([[6, 4, 5],
       [8, 6, 5],
       [1, 3, 5]])

In [37]:
arr5

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [2]:
arry=np.arange(1,51)

In [3]:
arry

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [4]:
arry1=np.array([[1,1,1],[1,1,1]])

In [5]:
arry1

array([[1, 1, 1],
       [1, 1, 1]])

In [8]:
arry2=np.array([[0,0,0],[0,0,0]])

In [10]:
arry2

array([[0, 0, 0],
       [0, 0, 0]])

In [11]:
matrix=np.random.rand(4,4)

In [12]:
matrix

array([[0.80727709, 0.12304522, 0.38623768, 0.28838621],
       [0.43859386, 0.66781281, 0.07908156, 0.09832017],
       [0.22377041, 0.44986896, 0.45517128, 0.70288338],
       [0.85933009, 0.65672808, 0.82559826, 0.76091166]])

In [57]:
random_mat=np.random.randint(0,100,size=(3,3))

In [58]:
random_mat

array([[11, 36, 92],
       [87, 80, 31],
       [35, 33,  0]])

In [2]:
import numpy as np

In [20]:
array3=np.zeros((2,3))

In [8]:
array3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
a=np.arange(0,4)

In [14]:
a

array([0, 1, 2, 3])

In [15]:
b=np.arange(4,8)

In [16]:
b

array([4, 5, 6, 7])

In [17]:
c=np.arange(4)

In [18]:
c

array([0, 1, 2, 3])

In [21]:
d=a+b

In [22]:
d

array([ 4,  6,  8, 10])

In [23]:
a-b

array([-4, -4, -4, -4])

In [24]:
a*c

array([0, 1, 4, 9])

In [25]:
a+b+c

array([ 4,  7, 10, 13])

In [26]:
a*b

array([ 0,  5, 12, 21])

In [27]:
b

array([4, 5, 6, 7])

In [28]:
b<8

array([ True,  True,  True,  True])

In [29]:
b>8

array([False, False, False, False])

In [30]:
b>6

array([False, False, False,  True])

In [32]:
e=np.arange(12)

In [33]:

e

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [34]:
f=e.reshape(3,4)

In [35]:
f

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [36]:
f.sum()

66

In [37]:
f.min()

0

In [38]:
f.max()

11

In [39]:
f.mean()

5.5

In [40]:
f.min(axis=1)     #axis1=raws

array([0, 4, 8])

In [41]:
f.min(axis=0)     #axis0=columns

array([0, 1, 2, 3])

In [42]:
f.sum(axis=0)

array([12, 15, 18, 21])

In [43]:
f.sum(axis=1)

array([ 6, 22, 38])

In [45]:
z=np.random.random((3,4))

In [46]:
z

array([[0.4905743 , 0.94169   , 0.24105213, 0.01527145],
       [0.52624472, 0.57392848, 0.05604649, 0.96778341],
       [0.58194803, 0.10737295, 0.06233401, 0.69515464]])

In [47]:
z.shape

(3, 4)

In [48]:
x=z.reshape(6,2)

In [49]:
x

array([[0.4905743 , 0.94169   ],
       [0.24105213, 0.01527145],
       [0.52624472, 0.57392848],
       [0.05604649, 0.96778341],
       [0.58194803, 0.10737295],
       [0.06233401, 0.69515464]])

In [50]:
x.ravel()      #1d or flatten cheyyan venditte 

array([0.4905743 , 0.94169   , 0.24105213, 0.01527145, 0.52624472,
       0.57392848, 0.05604649, 0.96778341, 0.58194803, 0.10737295,
       0.06233401, 0.69515464])

In [51]:
a=np.arange(4).reshape(2,2)

In [52]:
a

array([[0, 1],
       [2, 3]])

In [53]:
b=np.arange(4,8).reshape(2,2)

In [54]:
b

array([[4, 5],
       [6, 7]])

In [55]:
np.vstack((a,b))    #thaze thaze ayyit verum (verticle stack) 


array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [56]:
np.hstack((a,b))     #side side ayyit (horizontal stack)

array([[0, 1, 4, 5],
       [2, 3, 6, 7]])

In [57]:
np.eye(4,4)     #diagnally one ayirikum

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [58]:
a.dtype

dtype('int32')

In [59]:
h=np.array(['apple','orange','grape'])

In [60]:
h

array(['apple', 'orange', 'grape'], dtype='<U6')

In [64]:
q=np.array(['apple','orange','grape'],dtype='S')   #dtype string akki matti

In [63]:
q

array([b'apple', b'orange', b'grape'], dtype='|S6')

In [65]:
h=np.array(['apple','orange','grape'])

In [66]:
h

array(['apple', 'orange', 'grape'], dtype='<U6')

In [67]:
e=h.astype('S')    #unicode ne string akki matti

In [68]:
e

array([b'apple', b'orange', b'grape'], dtype='|S6')

In [69]:
o=e.copy()    #copy cheyyumbo orginal sadanathine mattam verulla 

In [70]:
o

array([b'apple', b'orange', b'grape'], dtype='|S6')

In [71]:
m=e.view()

In [72]:
m

array([b'apple', b'orange', b'grape'], dtype='|S6')

In [74]:
o[0]='banana'

In [75]:
o

array([b'banana', b'orange', b'grape'], dtype='|S6')

In [76]:
e    #e le marulla 

array([b'apple', b'orange', b'grape'], dtype='|S6')

In [77]:
m[0]='banana'

In [78]:
m

array([b'banana', b'orange', b'grape'], dtype='|S6')

In [79]:
e

array([b'banana', b'orange', b'grape'], dtype='|S6')

In [80]:
arr1=np.array([1,2])
arr2=np.array([3,4])


In [81]:
arr=np.concatenate((arr1,arr2))

In [82]:
arr

array([1, 2, 3, 4])

In [1]:
import numpy as np

In [16]:
a=np.array([1,2,3,4])

In [17]:
a

array([1, 2, 3, 4])

In [18]:
for x in a :
    print(x)

1
2
3
4


In [19]:
for x in a:
    if (x==3):
        print('3 is present in here')
    else:
        print('it is not 3')

it is not 3
it is not 3
3 is present in here
it is not 3


In [6]:
b=np.array([[1,2,3],[4,5,6]])

In [7]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
for x in b:
    print(x)

[1 2 3]
[4 5 6]


In [9]:
c=np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [13]:
for x in c:
    print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
for x in np.nditer(c):

    print(x)

1
2
3
4
5
6
7
8
9


In [20]:
a

array([1, 2, 3, 4])

In [24]:
for index,x in np.ndenumerate(a):
    print(index,x)

(0,) 1
(1,) 2
(2,) 3
(3,) 4


In [27]:
c

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [46]:
for index,x in np.ndenumerate(c):
    print(index,x)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 1, 0) 4
(0, 1, 1) 5
(0, 1, 2) 6
(0, 2, 0) 7
(0, 2, 1) 8
(0, 2, 2) 9


In [28]:
c.ndim

3

In [32]:
d=np.array([[[1,2,3,],[4,5,6],[7,8,9],[10,11,12]]])

In [33]:
d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]])

In [45]:
for index,x in np.ndenumerate(d):
    print(index,x)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 1, 0) 4
(0, 1, 1) 5
(0, 1, 2) 6
(0, 2, 0) 7
(0, 2, 1) 8
(0, 2, 2) 9
(0, 3, 0) 10
(0, 3, 1) 11
(0, 3, 2) 12


In [35]:
a

array([1, 2, 3, 4])

In [37]:
a1=np.array_split(a,2)

In [38]:
a1

[array([1, 2]), array([3, 4])]

In [41]:
a2=np.array_split(a,4)

In [42]:
a2

[array([1]), array([2]), array([3]), array([4])]

In [43]:
a3=np.array_split(a,3)

In [44]:
a3

[array([1, 2]), array([3]), array([4])]

In [47]:
a

array([1, 2, 3, 4])

In [48]:
e=np.where(a==4)

In [49]:
e

(array([3], dtype=int64),)

In [50]:
mp=np.array([1,2,3,4,3,4,5,6,1,2,1,1,4,5,7,1,7,1])

In [51]:
mp

array([1, 2, 3, 4, 3, 4, 5, 6, 1, 2, 1, 1, 4, 5, 7, 1, 7, 1])

In [52]:
np.where(mp==1)

(array([ 0,  8, 10, 11, 15, 17], dtype=int64),)

In [53]:
np.where(mp>3)

(array([ 3,  5,  6,  7, 12, 13, 14, 16], dtype=int64),)

In [54]:
np.where(mp %2==0)

(array([ 1,  3,  5,  7,  9, 12], dtype=int64),)

In [55]:
np.sort(mp)     #but mp le mattam verulla 

array([1, 1, 1, 1, 1, 1, 2, 2, 3, 3, 4, 4, 4, 5, 5, 6, 7, 7])

In [60]:
r=np.array([[[2,2,4],[3,6,5,],[8,1,3]]])

In [61]:
r

array([[[2, 2, 4],
        [3, 6, 5],
        [8, 1, 3]]])

In [62]:
np.sort(r)

array([[[2, 2, 4],
        [3, 5, 6],
        [1, 3, 8]]])

In [64]:
i=np.array([[['b','d','e'],['a','f','b'],['w','r','t']]])

In [65]:
i

array([[['b', 'd', 'e'],
        ['a', 'f', 'b'],
        ['w', 'r', 't']]], dtype='<U1')

In [66]:
np.sort(i)

array([[['b', 'd', 'e'],
        ['a', 'b', 'f'],
        ['r', 't', 'w']]], dtype='<U1')

In [1]:
import numpy as np

In [17]:
a=np.array([23,53,45,67])

In [18]:
x=[True,False,False,True]

In [19]:
new_a=a[x]

In [20]:
new_a

array([23, 67])

In [41]:
filter_array=[]

In [39]:
for i in a:
    if i > 46:
        filter_array.append(True)
    else:
        filter_array.append(False)

In [40]:
filter_array

[False, True, False, True]

In [24]:
new_a=a[filter_array]

In [25]:
new_a

array([53, 67])

In [43]:
filter_array2=[]

In [44]:
filter_array2=a>46

In [45]:
filter_array2

array([False,  True, False,  True])

In [46]:
e=np.linspace(1,5)    #1 to 5 ollade verum point ollade avvum

In [47]:
e

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [48]:
d=np.linspace(1,5,5)     #nammake 5 ennam madiyagil

In [49]:
d

array([1., 2., 3., 4., 5.])

In [50]:
r=np.linspace(1,5,2)

In [51]:
r

array([1., 5.])

In [52]:
g=np.arange(10).reshape(2,5)

In [53]:
g

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [54]:
np.vsplit(g,2)

[array([[0, 1, 2, 3, 4]]), array([[5, 6, 7, 8, 9]])]

In [56]:
c=np.arange(10,25)

In [57]:
c

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [60]:
np.hsplit(c,3)

[array([10, 11, 12, 13, 14]),
 array([15, 16, 17, 18, 19]),
 array([20, 21, 22, 23, 24])]